CREATE TABLE Users (
	id INT IDENTITY(1,1) PRIMARY KEY,
	CodeUser NVARCHAR(100) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Age INT NULL,
);

CREATE TABLE Schedule(
	id INT IDENTITY(1,1) PRIMARY KEY,
	Entrytime DATETIME NULL,
	ExitTime DATETIME NULL,
	UserId INT UNIQUE
	FOREIGN KEY (UserId) REFERENCES Users(id)
);

GO